[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "luracs"
version = "0.1.2"
description = "Gamma Spectroscopy Software"
requires-python = ">=3.10,<3.14"
authors = [
    {name = "Erik Ewald"}, 
    {name = "Malte Axner"}
    ]
license = { text = "GPL-3.0" }
readme = "README.md"
dependencies = [
    "bleak>=0.21",
    "numpy>=1.26",
    "pyqtgraph>=0.13.0",
    "PySide6>=6.5.0",
    "qasync>=0.27.0",
    "openpyxl>=3.0.0",
    "pyusb>=1.0.2",
    "lxml>=4.6.0",
    "libusb_package",
    "uncertainties",
    "plotext",
    "prompt_toolkit",
    "markdown",
    # "Scikit-Learn",
    # "SciPy",
    "fastapi",
    "uvicorn",
]

[project.optional-dependencies]
dev = ["pandas", "pyinstaller", "odfpy", "bumpver", "build", "twine"]


[tool.setuptools.packages.find]
where = ["."]
include = ["luracs*"]
exclude = ["tests*"]

[tool.setuptools.package-data]
luracs = ["resources/**/*"]

[project.scripts]
LuRaCs = "luracs.main:main"

[tool.bumpver]
current_version = "0.1.2"
version_pattern = "MAJOR.MINOR.PATCH"

commit = true
tag = true
push = false


[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]

"luracs/main.py" = [
    '__version__ = "{version}"',
]